export const GET_USER = 'GET_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const SET_FEATURED_PRODUCTS_DATA = 'SET_FEATURED_PRODUCTS_DATA'
export const SET_TRENDING_PRODUCTS_DATA = 'SET_TRENDING_PRODUCTS_DATA'